#########################################################################
#									#
# File ID: ./.travis.yml						#
# Author: Copyright (C) 2020, 2020  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0					#
#									#
# Configuration file for Travis CI build tests.				#
#									#
#########################################################################

#########################################################################
#									#
# Changelog								#
#									#
# Date		Author	Version	Description				#
#									#
# 11/02/2020	MG	1.0.1	Initial release.                        #
# 07/07/2020    MG      1.0.2   Bionic is now the minimum distribution  #
#                               due to dependencies built on LaunchPad. #
#									#
#########################################################################


language: bash

dist:
    - bionic

before_install:
    - sudo add-apt-repository ppa:m-grant-prg/utils -y
    - sudo apt-get update
    - sudo apt-get install -y txt2man txt2manwrap

script:
    - autoreconf -if .
    - ./configure --enable-silent-rules=yes
    - make --quiet
    - make --quiet check
    - make --quiet distcheck

